[project]
name = "nlp-midterm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy<2",
    "paddleocr==2.7.3",
    "paddlepaddle==2.6.2",
    "pymupdf>=1.27.2.3",
    "sentence-transformers>=5.6.0",
    "underthesea>=9.5.0",
]
